repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: 'dist/bundle.js'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.12.0
    hooks:
      - id: eslint
        files: >
          (?x)^(
            src/.*\.[jt]sx?
          )$
        types: [file]
        verbose: true
        additional_dependencies:
          ['eslint@8.57.0', '@eslint/js@9.4.0', 'eslint-config-prettier@9.1.0', 'typescript-eslint@7.12.0']
